### ISSUE TITLE
Optional straight lines

### ISSUE THREAD

**Issue by jhermann** [tsx/shireframe#4]
Hi, I find the abundance of squiggly lines nauseating, that should be optional. If you can do that, varying the thickness from 1-3px would probably also be a good alternative.

The like-hand-written fonts are great, keeps the "so you can ship tomorrow?" at bay. :smirk:

**Comment by tsx** [comment]
@jhermann I agree with you that squiggly lines should be optional. I will get to it tomorrow.
Thanks for suggestion! :+1:

**Comment by tsx** [comment]
@jhermann added a flag to remove line waviness. Check it out!
