### ISSUE TITLE
How does your custom elements work?

### ISSUE THREAD

**Issue by albatros2ko** [tsx/shireframe#5]
How does your custom elements implemented and happen to have their own default property and style? Do you use Polymer? By the way, **shireframe** really helped me kickstart my web projects.

**Comment by tsx** [comment]
Thank you for feedback! Glad to hear my project helped you.
Custom elements are actually AngularJS directives. You can read more about them in [AngularJS documentation](https://docs.angularjs.org/guide/directive). Polymer is not used in this project.

**Comment by albatros2ko** [comment]
Nice, thanks for the info 'mate!
