### ISSUE TITLE
Contribute?

### ISSUE THREAD

**Issue by jmatsushita** [tsx/shireframe#6]
Hi there,

I'm looking at shireframe and was wondering how I can contribute to add new tags?  Should I just add new tag definitions in `shireframe.js`? Do you have a build process of some sort?

Would be great to have some more detailed instructions!

Jun

**Comment by tsx** [comment]
Hey @jmatsushita,

thank you for your interest in Shireframe! 

Yes, feel free to add AngularJS directives to shireframe.js. Feel free to look around for helpers that simplify common patterns in directive declaration.

There's no build process, you can just create an HTML file for testing your tags, put a `<script src="shireframe-r.js"></script>` on top of it to load all required things automatically and hack away 😄.

Optinally, check out dev-server.js (you can run this with nodejs) - this is just a simple http server that serves your local files in current directory and has livereload watcher integrated - helps viewing changes in real time without alt-tabbing to refresh your browser, nice for quick turnaround.

I'll update the README with more detailed contribution guidelines soon.

Let me know if you need any other help or have any questions.

**Comment by webmaven** [comment]
So, looks like this issue can be closed, right?
